/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"

bool_t
xdr_OPERATION (XDR *xdrs, OPERATION *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_REQUEST (XDR *xdrs, REQUEST *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->index))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pid))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_OPERATION (xdrs, &objp->operation))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->res))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->number))
		 return FALSE;
	return TRUE;
}
